name: stock footage
favicon: null
layout_spectrum: 0.76026
typography_spectrum: 0.04043261846527457
title: OrlowskiDesigns Stock Footage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75102818-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5aaedd'
    - '#ffffff'
    - '#f8fefe'
    - '#57abda'
    - '#f4f9f9'
  brandStrength: 0.9187717635650188
  lightness: 0.2937014845665544
  saturation: 0.6849051287863404
  rhythmicContrast: 0.6609655558131635
purpose: []
